insert into public.guides (
  slug,
  title,
  prompt,
  category,
  icon,
  answer,
  answer_tone,
  summary,
  time,
  estimated_cost,
  estimated_savings,
  difficulty,
  supplies,
  essentials,
  skip_note,
  avoid,
  options,
  safety_note,
  professional_help,
  evidence,
  evidence_note,
  updated_at_label,
  featured,
  published,
  sort_order
)
values
(
    'brush-teeth',
    'Brushing your teeth',
    'Can I brush without toothpaste?',
    'Personal Care',
    '✦',
    'You can—but fluoride toothpaste adds proven cavity protection.',
    'depends',
    'Brushing does most of the plaque removal. Toothpaste is not required for the mechanical cleaning, but fluoride toothpaste helps prevent cavities and is the evidence-backed default for most people.',
    '2 minutes',
    '$0–$5 per month',
    'Varies by toothpaste and how much you use',
    'Easy',
    '["Soft-bristled toothbrush","Water","Fluoride toothpaste"]'::jsonb,
    '["Brush gently for two minutes, twice daily.","Use a soft-bristled brush and clean every tooth surface.","Clean between teeth once daily with floss or an interdental brush."]'::jsonb,
    'If you skip toothpaste occasionally, brush with water rather than substituting abrasive DIY powders. If you are cavity-prone, have dry mouth, wear braces, or have been advised to use fluoride, do not make toothpaste-free brushing your default without asking a dentist.',
    '[{"name":"Charcoal powders","reason":"Often abrasive, with limited evidence of benefit and potential to wear enamel."},{"name":"Lemon or vinegar","reason":"Acids can soften and erode tooth enamel."},{"name":"Aggressive brushing","reason":"More pressure does not clean better and can irritate gums."}]'::jsonb,
    '[{"name":"Use less toothpaste","detail":"A pea-sized amount is enough for adults; more foam does not mean more cleaning.","label":"USE LESS"},{"name":"Choose a simple fluoride toothpaste","detail":"Look for an ADA-accepted option without extra whitening claims if sensitivity is a concern.","label":"SIMPLE SWAP"},{"name":"Brush with water occasionally","detail":"Better than skipping the brush entirely, but it does not provide fluoride protection.","label":"PRODUCT"}]'::jsonb,
    'Do not use acidic or abrasive DIY substitutes that can damage enamel.',
    '["Tooth pain, swelling, bleeding that persists, or a broken tooth","Frequent cavities, dry mouth, braces, or personalized fluoride needs"]'::jsonb,
    'Strong',
    'Strong evidence supports twice-daily brushing with fluoride toothpaste for cavity prevention. Individual dental needs vary.',
    'July 2026',
    true,
    true,
    1
  ),
(
    'deodorant',
    'Using deodorant',
    'Do I need deodorant every day?',
    'Personal Care',
    '○',
    'No. Use it when odor control matters to you.',
    'yes',
    'Body odor comes mainly from skin bacteria breaking down sweat. Deodorant reduces odor; antiperspirant reduces sweat. Neither is required for health.',
    '1–2 minutes',
    '$0–$10 per month',
    'Up to the cost of products you choose not to use',
    'Easy',
    '["Water","Gentle cleanser if needed","Clean clothing"]'::jsonb,
    '["Wash and fully dry the underarm area.","Wear breathable clothing and change damp shirts.","Use deodorant only as often as you find useful."]'::jsonb,
    'You can skip deodorant entirely. If odor is the issue, washing, drying, and changing clothing may be enough. Persistent new or unusual odor can have medical causes and is worth discussing with a clinician.',
    '[{"name":"Products that sting or cause a rash","reason":"Fragrance, baking soda, acids, and essential oils can all irritate sensitive skin."},{"name":"Applying to broken skin","reason":"Freshly shaved or irritated skin is more likely to react."},{"name":"Fear-based aluminum claims","reason":"Current evidence has not established that approved aluminum antiperspirants cause breast cancer."}]'::jsonb,
    '[{"name":"Use nothing","detail":"Wash, dry, and reassess. You may not need another step.","label":"USE LESS"},{"name":"Fragrance-free deodorant","detail":"A short ingredient list may reduce irritation; patch test first.","label":"SIMPLE SWAP"},{"name":"Antiperspirant when needed","detail":"Useful for sweat control. Apply to dry skin, often at night, as directed.","label":"PRODUCT"}]'::jsonb,
    'Stop using products that cause burning, swelling, or a persistent rash.',
    '["A new, strong, or unusual odor that does not improve with washing","Painful lumps, drainage, severe sweating, or a persistent rash"]'::jsonb,
    'Moderate',
    'Deodorant use is a personal preference. Ingredient tolerance varies more than marketing categories suggest.',
    'July 2026',
    true,
    true,
    2
  ),
(
    'shower',
    'Taking a shower',
    'Do I need soap everywhere?',
    'Personal Care',
    '⌁',
    'Usually not. Focus cleanser where sweat, odor, or soil collects.',
    'yes',
    'Water and gentle friction are enough for much of the body. Over-cleansing can dry or irritate skin, especially with hot water and fragranced products.',
    '5–10 minutes',
    '$0–$8 per month',
    'Varies by water use and products skipped',
    'Easy',
    '["Warm water","Gentle cleanser for targeted areas","Clean towel"]'::jsonb,
    '["Use warm—not very hot—water.","Clean hands, underarms, groin, feet, and visibly soiled areas.","Pat dry and moisturize dry areas while skin is slightly damp."]'::jsonb,
    'You can usually skip cleanser on arms, legs, and torso unless they are dirty, oily, or exposed to something that needs removal. Individual skin conditions may require different care.',
    '[{"name":"Very hot, long showers","reason":"They can strip skin oils and worsen dryness."},{"name":"Harsh scrubbing","reason":"Loofahs and rough exfoliation can irritate the skin barrier."},{"name":"Heavy fragrance","reason":"A common trigger for irritation or contact allergy."}]'::jsonb,
    '[{"name":"Targeted washing","detail":"Use cleanser only where it is doing a clear job.","label":"USE LESS"},{"name":"Fragrance-free gentle cleanser","detail":"Choose a simple syndet or mild wash for sensitive or dry skin.","label":"SIMPLE SWAP"}]'::jsonb,
    'Use extra care with very hot water, slippery surfaces, and products that irritate skin.',
    '["A spreading rash, signs of infection, or severe persistent itching","Skin conditions that worsen despite gentle care"]'::jsonb,
    'Moderate',
    'Dermatology guidance generally favors short, warm showers and gentle, targeted cleansing for dry or sensitive skin.',
    'July 2026',
    true,
    true,
    3
  ),
(
    'wash-hair',
    'Washing your hair',
    'Do I need shampoo every day?',
    'Personal Care',
    '≈',
    'Usually not. Wash based on your scalp—not a fixed schedule.',
    'yes',
    'Hair texture, scalp oil, styling products, exercise, and skin conditions all change how often shampoo is useful. The scalp is the target; the ends rarely need direct shampoo.',
    '5–15 minutes',
    '$0–$10 per month',
    'Varies with wash frequency and product use',
    'Easy',
    '["Water","Shampoo when needed","Conditioner if useful"]'::jsonb,
    '["Apply shampoo primarily to the scalp.","Rinse thoroughly and let suds run through the lengths.","Adjust frequency if the scalp becomes itchy, oily, flaky, or irritated."]'::jsonb,
    'Water-only days can work between washes. Going indefinitely without shampoo is not automatically healthier, particularly with heavy product buildup or scalp conditions.',
    '[{"name":"Undiluted essential oils","reason":"They can irritate the scalp and cause contact allergy."},{"name":"Scratching with fingernails","reason":"This can damage irritated skin."}]'::jsonb,
    '[{"name":"Wash less often","detail":"Reduce gradually and let scalp comfort—not a trend—set the schedule.","label":"USE LESS"},{"name":"Simple fragrance-free shampoo","detail":"Useful when fragrance or botanicals trigger irritation.","label":"SIMPLE SWAP"}]'::jsonb,
    'Avoid putting undiluted essential oils or harsh household ingredients on the scalp.',
    '["Sudden or patchy hair loss","Pain, sores, drainage, or persistent severe scaling"]'::jsonb,
    'Moderate',
    'There is no universal ideal shampoo schedule. Persistent flaking, pain, or hair loss warrants professional evaluation.',
    'July 2026',
    false,
    true,
    4
  ),
(
    'laundry',
    'Doing laundry',
    'How much detergent do I really need?',
    'Cleaning',
    '□',
    'Often less than the label’s largest dose.',
    'yes',
    'Using too much detergent can leave residue, trap soil, and require extra rinsing. Dose for load size, soil level, water hardness, and machine type.',
    '5 minutes of hands-on work',
    '$0.10–$0.50 per load',
    'Varies with detergent dose and avoided rewashing',
    'Easy',
    '["Washing machine or wash basin","Measured detergent","Water"]'::jsonb,
    '["Start with the smallest recommended dose.","Do not pack the machine so tightly that items cannot move.","Use an extra rinse only if residue or sensitivity is a problem."]'::jsonb,
    'Lightly worn items may only need airing out. Detergent is still useful for body oils, visible soil, illness-related laundry, and odors.',
    '[{"name":"Scent boosters","reason":"They add fragrance but do not improve cleaning."},{"name":"Fabric softener by default","reason":"It can coat fibers and reduce towel absorbency."},{"name":"Mixing cleaning chemicals","reason":"Some combinations can release dangerous gases."}]'::jsonb,
    '[{"name":"Air and rewear","detail":"For clean, lightly worn items, hanging them up may be enough.","label":"USE LESS"},{"name":"Fragrance-free detergent","detail":"Choose a concentrated product and measure the dose.","label":"SIMPLE SWAP"}]'::jsonb,
    'Never mix bleach with ammonia, acids, or other cleaners.',
    '["A leaking, sparking, smoking, or repeatedly overflowing machine","Contaminated occupational or hazardous-material laundry"]'::jsonb,
    'Moderate',
    'Laundry needs vary with water, machine, fabric, and soil. Product instructions remain important for disinfection or occupational exposure.',
    'July 2026',
    true,
    true,
    5
  ),
(
    'wash-dishes',
    'Washing dishes',
    'Do I need antibacterial dish soap?',
    'Cleaning',
    '◒',
    'Usually not. Regular dish soap and friction do the job.',
    'yes',
    'Surfactants loosen grease and food so water can carry them away. For routine dishwashing, technique and thorough rinsing matter more than antibacterial marketing.',
    '5–20 minutes',
    'Usually under $1 per load',
    'Varies with soap and water use',
    'Easy',
    '["Warm water","Dish soap","Clean brush, cloth, or sponge"]'::jsonb,
    '["Remove food scraps first.","Use a small amount of dish soap with warm water.","Rinse and allow items to dry completely."]'::jsonb,
    'Plain water may be enough for a glass that only held water. Greasy, protein-rich, or contaminated dishes need detergent and proper cleaning.',
    '[{"name":"Overfilling the sink with soap","reason":"More suds can mean more residue and rinsing without better cleaning."},{"name":"Old, wet sponges","reason":"They hold food and moisture; clean, dry, and replace them regularly."}]'::jsonb,
    '[{"name":"Use one small drop","detail":"Increase only when grease or load size requires it.","label":"USE LESS"},{"name":"Fragrance-free dish soap","detail":"A practical choice for sensitive skin or fragrance avoidance.","label":"SIMPLE SWAP"}]'::jsonb,
    'Handle knives and broken glass separately, and never mix cleaning chemicals.',
    '["A sink that repeatedly backs up or leaks into cabinets or walls","Suspected sewage contamination"]'::jsonb,
    'Strong',
    'Soap, water, friction, rinsing, and drying are established foundations of routine cleaning.',
    'July 2026',
    false,
    true,
    6
  ),
(
    'moisturize',
    'Moisturizing your skin',
    'Do I need body lotion?',
    'Personal Care',
    '◇',
    'Only if your skin is dry, tight, itchy, or needs barrier support.',
    'yes',
    'Moisturizer reduces water loss and supports the skin barrier. If your skin feels comfortable, applying lotion everywhere is optional.',
    '1–3 minutes',
    '$0–$15 per month',
    'Up to the cost of unnecessary specialty products',
    'Easy',
    '["A simple moisturizer only where needed"]'::jsonb,
    '["Apply to dry areas rather than automatically covering the whole body.","Use after bathing while skin is slightly damp.","Choose thicker creams or ointments for very dry areas."]'::jsonb,
    'Normal, comfortable skin does not require lotion. Red, cracked, persistently itchy, or changing skin needs more than product experimentation.',
    '[{"name":"Fragrance on irritated skin","reason":"It can increase the chance of stinging or contact allergy."},{"name":"Long ingredient lists for no clear reason","reason":"More ingredients create more opportunities for sensitivity without guaranteed benefit."}]'::jsonb,
    '[{"name":"Spot moisturize","detail":"Use only on hands, shins, elbows, or other areas that need it.","label":"USE LESS"},{"name":"Plain fragrance-free cream","detail":"Look for a simple formula in a tube or tub.","label":"SIMPLE SWAP"}]'::jsonb,
    'Stop using a product that causes burning, swelling, hives, or a worsening rash.',
    '["Cracked, bleeding, infected, or persistently inflamed skin","A changing mole or unexplained skin change"]'::jsonb,
    'Strong',
    'Moisturizers are well supported for dry skin and barrier disorders, but routine full-body use is a preference.',
    'July 2026',
    false,
    true,
    7
  ),
(
    'clean-counters',
    'Cleaning counters',
    'Do I need disinfectant every time?',
    'Cleaning',
    '—',
    'No. Cleaning and disinfecting are different jobs.',
    'yes',
    'Soap or a general cleaner removes everyday dirt and many microbes. Disinfectant is useful for specific higher-risk situations, not every routine wipe-down.',
    '5–10 minutes',
    'Usually under $1 per cleaning',
    'Varies with specialized products avoided',
    'Easy',
    '["Reusable cloth","Soap or surface-appropriate cleaner","Water"]'::jsonb,
    '["Remove crumbs and visible soil.","Clean with soap or an appropriate surface cleaner.","Disinfect only when needed and follow the product’s contact time."]'::jsonb,
    'Skip disinfectant for most routine cleaning. Consider it after raw meat contamination, certain illnesses, or when public-health guidance calls for it.',
    '[{"name":"Mixing bleach with other cleaners","reason":"Mixing can create toxic gases."},{"name":"Spraying near food or faces","reason":"Apply carefully, ventilate, and follow the label."},{"name":"Ignoring contact time","reason":"A disinfectant wiped away immediately may not work as intended."}]'::jsonb,
    '[{"name":"Soap and water","detail":"The default for ordinary dirt and day-to-day counter cleaning.","label":"USE LESS"},{"name":"Surface-appropriate cleaner","detail":"Choose based on the counter material, not broad “natural” claims.","label":"SIMPLE SWAP"}]'::jsonb,
    'Ventilate the area and never mix bleach with ammonia, acids, or other cleaners.',
    '["Large sewage, mold, chemical, or biohazard contamination","A surface problem caused by an active leak or structural damage"]'::jsonb,
    'Strong',
    'Public-health guidance distinguishes routine cleaning from targeted disinfection. Always follow surface and product instructions.',
    'July 2026',
    false,
    true,
    8
  ),
(
    'routine-pest-control',
    'Routine pest control',
    'Can I try something before paying for recurring pest control?',
    'Household Services',
    '⌂',
    'Often, yes. Start by removing food, water, shelter, and entry points.',
    'depends',
    'Many minor ant, roach, and occasional-invader problems improve when you identify the pest, remove what attracts it, seal entry points, and use a targeted control. The right response depends on the species and severity.',
    '30–90 minutes, plus monitoring',
    '$10–$50 for basic supplies',
    'Potentially $100–$400 compared with a recurring general service',
    'Moderate',
    '["Flashlight","Sealed food containers","Caulk or door sweep","Species-appropriate traps or enclosed bait"]'::jsonb,
    '["Identify the pest before choosing a treatment.","Remove accessible food, standing water, clutter, and waste.","Seal small gaps and repair screens or door sweeps.","Use the least hazardous targeted trap or bait that fits the pest, following the label exactly.","Monitor activity for one to two weeks and record where it appears."]'::jsonb,
    'You may be able to skip a recurring general spray when the problem is minor and the cause can be corrected. Do not delay professional help for destructive, dangerous, or rapidly spreading pests.',
    '[{"name":"Spraying before identifying the pest","reason":"The wrong treatment may fail, scatter pests, or create unnecessary exposure."},{"name":"Foggers and broad indoor spraying","reason":"They can increase pesticide exposure and may not reach where pests live."},{"name":"Unlabeled DIY chemical mixtures","reason":"Mixing or repurposing chemicals can poison people, pets, or wildlife."}]'::jsonb,
    '[{"name":"Remove the attraction","detail":"Store food, clean crumbs and grease, fix drips, and empty waste regularly.","label":"DIY FIRST"},{"name":"Block the route","detail":"Seal gaps, repair screens, and add a door sweep where pests enter.","label":"SIMPLE SWAP"},{"name":"Use a targeted trap or bait","detail":"Choose a product labeled for the identified pest and keep it away from children and pets.","label":"PRODUCT"}]'::jsonb,
    'Read and follow every pesticide label. Keep traps and baits away from children, pets, food, and food-preparation surfaces.',
    '["Termites, bed bugs, stinging-insect nests, venomous pests, or wildlife","Rodents inside living areas, extensive droppings, or possible disease exposure","A large, recurring, or unidentified infestation","Any treatment requiring restricted chemicals, ladders, roofs, or wall access"]'::jsonb,
    'Moderate',
    'Integrated pest management emphasizes identification, sanitation, exclusion, monitoring, and targeted controls before routine broad pesticide use. Results depend heavily on the pest and building.',
    'July 2026',
    true,
    true,
    9
  )
on conflict (slug) do update set
  title = excluded.title,
  prompt = excluded.prompt,
  category = excluded.category,
  icon = excluded.icon,
  answer = excluded.answer,
  answer_tone = excluded.answer_tone,
  summary = excluded.summary,
  time = excluded.time,
  estimated_cost = excluded.estimated_cost,
  estimated_savings = excluded.estimated_savings,
  difficulty = excluded.difficulty,
  supplies = excluded.supplies,
  essentials = excluded.essentials,
  skip_note = excluded.skip_note,
  avoid = excluded.avoid,
  options = excluded.options,
  safety_note = excluded.safety_note,
  professional_help = excluded.professional_help,
  evidence = excluded.evidence,
  evidence_note = excluded.evidence_note,
  updated_at_label = excluded.updated_at_label,
  featured = excluded.featured,
  published = excluded.published,
  sort_order = excluded.sort_order,
  updated_at = now();
