import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = resolve(projectRoot, 'src/config/generatedEnv.ts');
const webOutputPath = resolve(projectRoot, 'web/.env.local');

const supabaseUrl = process.env.SUPABASE_URL?.trim() ?? '';
const supabasePublishableKey =
  process.env.SUPABASE_PUBLISHABLE_KEY?.trim() ?? '';

if (Boolean(supabaseUrl) !== Boolean(supabasePublishableKey)) {
  throw new Error(
    'Set both SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY, or leave both blank for offline mode.',
  );
}

if (supabaseUrl) {
  const parsedUrl = new URL(supabaseUrl);
  if (!['https:', 'http:'].includes(parsedUrl.protocol)) {
    throw new Error('SUPABASE_URL must use HTTPS or HTTP.');
  }
}

const generated =
  `// Generated by scripts/generate-env.mjs. Do not edit or commit.\n` +
  `export const env = Object.freeze({\n` +
  `  supabaseUrl: ${JSON.stringify(supabaseUrl)},\n` +
  `  supabasePublishableKey: ${JSON.stringify(supabasePublishableKey)},\n` +
  `});\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, { mode: 0o600 });

if (supabaseUrl) {
  const webGenerated =
    `NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}\n` +
    `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${supabasePublishableKey}\n`;
  await writeFile(webOutputPath, webGenerated, { mode: 0o600 });
} else {
  await rm(webOutputPath, { force: true });
}

console.log(
  supabaseUrl
    ? 'Generated Supabase configuration.'
    : 'Generated offline development configuration.',
);
