import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = resolve(projectRoot, 'src/config/generatedEnv.ts');
const webOutputPath = resolve(projectRoot, 'web/.env.local');

const supabaseUrl = process.env.SUPABASE_URL?.trim() ?? '';
const supabasePublishableKey =
  process.env.SUPABASE_PUBLISHABLE_KEY?.trim() ?? '';
const siteUrl = process.env.SITE_URL?.trim() ?? 'http://localhost:3000';
const supportEmail = process.env.SUPPORT_EMAIL?.trim() ?? '';

if (Boolean(supabaseUrl) !== Boolean(supabasePublishableKey)) {
  throw new Error(
    'Set both SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY, or leave both blank for offline mode.',
  );
}

if (supabaseUrl) {
  const parsedUrl = new URL(supabaseUrl);
  if (!['https:', 'http:'].includes(parsedUrl.protocol)) {
    throw new Error('SUPABASE_URL must use HTTPS or HTTP.');
  }
}

const parsedSiteUrl = new URL(siteUrl);
if (!['https:', 'http:'].includes(parsedSiteUrl.protocol)) {
  throw new Error('SITE_URL must use HTTPS or HTTP.');
}

if (supportEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(supportEmail)) {
  throw new Error('SUPPORT_EMAIL must be a valid email address.');
}

const generated =
  `// Generated by scripts/generate-env.mjs. Do not edit or commit.\n` +
  `export const env = Object.freeze({\n` +
  `  supabaseUrl: ${JSON.stringify(supabaseUrl)},\n` +
  `  supabasePublishableKey: ${JSON.stringify(supabasePublishableKey)},\n` +
  `});\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, { mode: 0o600 });

if (supabaseUrl) {
  const webGenerated =
    `NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}\n` +
    `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${supabasePublishableKey}\n` +
    `NEXT_PUBLIC_SITE_URL=${siteUrl}\n` +
    `NEXT_PUBLIC_SUPPORT_EMAIL=${supportEmail}\n`;
  await writeFile(webOutputPath, webGenerated, { mode: 0o600 });
} else {
  await writeFile(
    webOutputPath,
    `NEXT_PUBLIC_SITE_URL=${siteUrl}\n` +
      `NEXT_PUBLIC_SUPPORT_EMAIL=${supportEmail}\n`,
    { mode: 0o600 },
  );
}

console.log(
  supabaseUrl
    ? 'Generated Supabase configuration.'
    : 'Generated offline development configuration.',
);
