import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = resolve(projectRoot, '.env');
const outputPath = resolve(projectRoot, 'src/config/generatedEnv.ts');

function parseEnv(contents) {
  return Object.fromEntries(
    contents
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#'))
      .map(line => {
        const separator = line.indexOf('=');
        return separator === -1
          ? [line, '']
          : [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

let values = {};
try {
  values = parseEnv(await readFile(sourcePath, 'utf8'));
} catch (error) {
  if (error?.code !== 'ENOENT') {
    throw error;
  }
}

const supabaseUrl = values.SUPABASE_URL?.trim() ?? '';
const supabasePublishableKey = values.SUPABASE_PUBLISHABLE_KEY?.trim() ?? '';

if (Boolean(supabaseUrl) !== Boolean(supabasePublishableKey)) {
  throw new Error(
    'Set both SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY, or leave both blank for offline mode.',
  );
}

if (supabaseUrl) {
  const parsedUrl = new URL(supabaseUrl);
  if (!['https:', 'http:'].includes(parsedUrl.protocol)) {
    throw new Error('SUPABASE_URL must use HTTPS or HTTP.');
  }
}

const generated =
  `// Generated by scripts/generate-env.mjs. Do not edit or commit.\n` +
  `export const env = Object.freeze({\n` +
  `  supabaseUrl: ${JSON.stringify(supabaseUrl)},\n` +
  `  supabasePublishableKey: ${JSON.stringify(supabasePublishableKey)},\n` +
  `});\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, { mode: 0o600 });
console.log(
  supabaseUrl
    ? 'Generated Supabase configuration.'
    : 'Generated offline development configuration.',
);
