import { StyleSheet } from 'react-native';

export const COLORS = {
  ink: '#171714',
  paper: '#F4F0E8',
  card: '#FFFCF6',
  lime: '#D9F65A',
  orange: '#FF6B3D',
  muted: '#6B6962',
  line: '#D8D3C8',
  white: '#FFFFFF',
  green: '#1F5C45',
};

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: COLORS.paper,
  },
  topBar: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  wordmark: {
    color: COLORS.ink,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  savedButton: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  savedButtonActive: {
    backgroundColor: COLORS.lime,
  },
  savedButtonText: {
    color: COLORS.ink,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  countBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 5,
    borderRadius: 9,
    backgroundColor: COLORS.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadgeText: {
    color: COLORS.card,
    fontSize: 10,
    fontWeight: '800',
  },
  scrollContent: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 20,
  },
  hero: {
    paddingTop: 38,
    paddingBottom: 28,
  },
  kickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 17,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.orange,
  },
  kicker: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  heroTitle: {
    color: COLORS.ink,
    fontSize: 48,
    lineHeight: 49,
    fontWeight: '900',
    letterSpacing: -2.4,
    maxWidth: 650,
  },
  heroBody: {
    color: COLORS.muted,
    fontSize: 17,
    lineHeight: 25,
    marginTop: 18,
    maxWidth: 480,
  },
  searchWrap: {
    minHeight: 58,
    backgroundColor: COLORS.card,
    borderColor: COLORS.ink,
    borderWidth: 2,
    borderRadius: 4,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    shadowColor: COLORS.ink,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  searchInput: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 16,
    paddingVertical: 14,
  },
  chips: {
    gap: 8,
    paddingTop: 22,
    paddingBottom: 9,
    paddingRight: 20,
  },
  chip: {
    paddingHorizontal: 15,
    paddingVertical: 9,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  chipActive: {
    backgroundColor: COLORS.ink,
    borderColor: COLORS.ink,
  },
  chipText: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  chipTextActive: {
    color: COLORS.card,
  },
  listHeader: {
    marginTop: 32,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listTitle: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  listMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resultCount: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  guideList: {
    borderTopWidth: 1.5,
    borderTopColor: COLORS.ink,
  },
  guideCard: {
    minHeight: 120,
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.ink,
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: COLORS.paper,
  },
  pressed: {
    backgroundColor: COLORS.lime,
  },
  cardNumberWrap: {
    width: 44,
    paddingTop: 23,
  },
  cardNumber: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.7,
  },
  cardMain: {
    flex: 1,
    paddingVertical: 21,
    paddingRight: 12,
  },
  cardCategory: {
    color: COLORS.orange,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.2,
    marginBottom: 7,
  },
  cardTitle: {
    color: COLORS.ink,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  cardPrompt: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  cardArrow: {
    width: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: COLORS.line,
  },
  emptySearch: {
    alignItems: 'center',
    paddingVertical: 64,
    paddingHorizontal: 30,
  },
  emptySymbol: {
    color: COLORS.ink,
    fontSize: 54,
    fontWeight: '900',
    marginBottom: 10,
  },
  emptyTitle: {
    color: COLORS.ink,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  emptyBody: {
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 9,
    maxWidth: 360,
  },
  promise: {
    backgroundColor: COLORS.ink,
    marginTop: 42,
    padding: 24,
    borderRadius: 4,
  },
  promiseLabel: {
    color: COLORS.lime,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  promiseTitle: {
    color: COLORS.card,
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -1,
    marginTop: 18,
  },
  promiseBody: {
    color: '#C8C5BC',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    maxWidth: 440,
  },
  savedHero: {
    paddingTop: 64,
    paddingBottom: 34,
  },
  pageEyebrow: {
    color: COLORS.orange,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
    marginBottom: 15,
  },
  pageTitle: {
    color: COLORS.ink,
    fontSize: 48,
    lineHeight: 50,
    fontWeight: '900',
    letterSpacing: -2,
  },
  pageBody: {
    color: COLORS.muted,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 14,
    maxWidth: 430,
  },
  savedEmpty: {
    minHeight: 390,
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: COLORS.ink,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
  },
  savedEmptyIcon: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: COLORS.lime,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  primaryButton: {
    marginTop: 24,
    minHeight: 48,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
    borderRadius: 3,
    backgroundColor: COLORS.lime,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  primaryButtonText: {
    color: COLORS.ink,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  detailShell: {
    flex: 1,
  },
  detailTopBar: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailWordmark: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonSaved: {
    backgroundColor: COLORS.lime,
  },
  detailContent: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 20,
  },
  detailHero: {
    paddingTop: 34,
    paddingBottom: 28,
  },
  detailCategory: {
    color: COLORS.orange,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.4,
    marginBottom: 17,
  },
  detailTitle: {
    color: COLORS.ink,
    fontSize: 46,
    lineHeight: 48,
    fontWeight: '900',
    letterSpacing: -2.2,
  },
  detailPrompt: {
    color: COLORS.muted,
    fontSize: 18,
    lineHeight: 25,
    marginTop: 12,
  },
  answerCard: {
    backgroundColor: COLORS.lime,
    borderWidth: 2,
    borderColor: COLORS.ink,
    borderRadius: 4,
    padding: 22,
    shadowColor: COLORS.ink,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
    marginBottom: 46,
  },
  answerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  answerLabel: {
    color: COLORS.ink,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  answerIcon: {
    color: COLORS.ink,
    fontSize: 25,
    fontWeight: '900',
  },
  answerText: {
    color: COLORS.ink,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: '900',
    letterSpacing: -1,
    marginTop: 25,
    maxWidth: 570,
  },
  answerSummary: {
    color: '#3A3A32',
    fontSize: 15,
    lineHeight: 23,
    marginTop: 13,
    maxWidth: 600,
  },
  detailSection: {
    marginBottom: 45,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.ink,
    paddingBottom: 11,
    marginBottom: 18,
  },
  sectionNumber: {
    width: 39,
    color: COLORS.orange,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  sectionTitle: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  stepList: {
    gap: 12,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 13,
  },
  stepNumber: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: COLORS.ink,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  stepNumberText: {
    color: COLORS.card,
    fontSize: 11,
    fontWeight: '900',
  },
  stepText: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 16,
    lineHeight: 24,
    paddingTop: 2,
  },
  factGrid: {
    gap: 10,
  },
  factCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 3,
    padding: 15,
  },
  factLabel: {
    color: COLORS.orange,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  factValue: {
    color: COLORS.ink,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    marginTop: 6,
  },
  supplyHeading: {
    color: COLORS.ink,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    marginTop: 20,
  },
  supplyText: {
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: 23,
    marginTop: 7,
  },
  skipCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
    borderRadius: 3,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  skipText: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 15,
    lineHeight: 23,
  },
  avoidList: {
    gap: 0,
  },
  avoidRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 13,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  avoidMark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.orange,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  avoidCopy: {
    flex: 1,
  },
  avoidName: {
    color: COLORS.ink,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '800',
  },
  avoidReason: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
  optionList: {
    gap: 12,
  },
  optionCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1.5,
    borderColor: COLORS.ink,
    borderRadius: 3,
    padding: 18,
  },
  optionLabel: {
    alignSelf: 'flex-start',
    color: COLORS.ink,
    backgroundColor: COLORS.lime,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginBottom: 13,
  },
  optionName: {
    color: COLORS.ink,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  optionDetail: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
  },
  safetyCard: {
    backgroundColor: '#FFF1E9',
    borderWidth: 1.5,
    borderColor: COLORS.orange,
    borderRadius: 3,
    padding: 18,
  },
  safetyLabel: {
    color: COLORS.orange,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  safetyText: {
    color: COLORS.ink,
    fontSize: 15,
    lineHeight: 23,
    marginTop: 8,
  },
  proHeading: {
    color: COLORS.ink,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    marginTop: 22,
    marginBottom: 8,
  },
  proRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    marginTop: 7,
  },
  proBullet: {
    color: COLORS.orange,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
  },
  proText: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 14,
    lineHeight: 21,
  },
  evidenceCard: {
    backgroundColor: COLORS.ink,
    borderRadius: 4,
    padding: 22,
    marginTop: 2,
  },
  evidenceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  evidenceEyebrow: {
    color: COLORS.lime,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  evidenceStrength: {
    color: COLORS.card,
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.8,
    marginTop: 5,
  },
  evidenceBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 5,
    paddingBottom: 4,
  },
  evidenceBar: {
    width: 9,
    height: 18,
    backgroundColor: '#4B4B46',
  },
  evidenceBarActive: {
    height: 28,
    backgroundColor: COLORS.lime,
  },
  evidenceNote: {
    color: '#D2CFC7',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 19,
    maxWidth: 590,
  },
  updated: {
    color: '#86847D',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.9,
    marginTop: 18,
  },
  disclaimer: {
    color: COLORS.muted,
    fontSize: 11,
    lineHeight: 17,
    textAlign: 'center',
    maxWidth: 510,
    alignSelf: 'center',
    marginTop: 20,
    paddingHorizontal: 20,
  },
});
